### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by andreasabel** [dev-drprasad/delete-tag-and-release#11]
Please add a changelog (CHANGELOG.md) and maintain it for future releases.

**Comment by thadguidry** [comment]
It's better I think to just use proper Release Notes for the tags since GitHub makes them nearly automatic and when a new version is published you can read them independently on each release version.  But if there's something else I am missing let me know.

**Comment by andreasabel** [comment]
Ok, that's fine.  A hand-written changelog is easier to read, but yeah, it is some extra effort to maintain.

**Comment by thadguidry** [comment]
@andreasabel you can see release notes (a change log) at any time by going to `tags` and then clicking on the **notes** link next to each release version (tag).  https://github.com/dev-drprasad/delete-tag-and-release/tags
