### ISSUE TITLE
Deleting v0.2.0 breaks our CI

### ISSUE THREAD

**Issue by nitsanh** [dev-drprasad/delete-tag-and-release#19]
Hi, I noticed you released v0.2.1 a couple of hours ago. We've been using 0.2.0 in our CI but I guess you deleted this tag after releasing 0.2.1.
It'll be hard for us to update to 0.2.1 all over our repos, any chance you can bring back 0.2.0 as well?

**Comment by 134130** [comment]
The maintainer can add v0.2.0 tag on same git object of v0.2.1.

**Comment by nitsanh** [comment]
If it doesn't break backwards compatibility that works for me

**Comment by thadguidry** [comment]
Hi @nitsanh Please update to v0.2.1

**Comment by rishabh-arya95** [comment]
+1, fortunately we were using reusable workflows so changes needed to be made in one repo

**Comment by nitsanh** [comment]
> Hi @nitsanh Please update to v0.2.1

wow @thadguidry, that's a really great way of updating your repo. Thank you.

**Comment by nitsanh** [comment]
> +1 fortunately, we were using reusable workflows so changes needed to be made in one repo

Us too, but all our other workflows use a specific version of our reusable workflow, now I need to override this tag on my end and hope it doesn't break.

**Comment by 134130** [comment]
Fundamentally, The action should provide v0.2 tag also.
