### ISSUE TITLE
Create a new prerelease for v1.0

### ISSUE THREAD

**Issue by thadguidry** [dev-drprasad/delete-tag-and-release#32]
@wardellbagby Let me know in this issue when we might want to do this.

**Comment by wardellbagby** [comment]
These are the big things on my mind before a 1.0 pre-release:

1. Automating tests against an actual repo. I'm not certain of how feasible this is but I do have a working branch that actually uses a real GitHuv repo to create releases and tags and then uses this Action to delete those releases and tags. I'm not sure if it's something we can actually add as something that runs on PRs but once I get it done, it might still be worth adding to this repo as a manual step before release. I'm not super confident in this though, so I'm still exploring.

2. Running all of the existing checks against new commits to master as well as PRs. This could give us confidence right before cutting a release that things are good. This is an easy change to make as well; just wanted to make sure it's a good idea.

I plan on using this weekend to think of more test cases and manually running those tests against the old and this potentially new version as well just to be extra sure that functionality hasn't changed. If that all goes well (I'll report back as soon as I know), then I think a pre-release early next week would be good.

**Comment by wardellbagby** [comment]
Took me longer than I meant to but I think we're good to do a pre-release and let that get in the hands of folks.

**Comment by thadguidry** [comment]
Ok sounds good.  Will do the 1.0 prerelease when I get back home later.

**Comment by thadguidry** [comment]
DONE !  https://github.com/dev-drprasad/delete-tag-and-release/releases/tag/v1.0
