### ISSUE TITLE
[Feature request] Ability to delete multiple tags at once

### ISSUE THREAD

**Issue by okuramasafumi** [dev-drprasad/delete-tag-and-release#37]
It seems that `tag_name` [accepts String only](https://github.com/dev-drprasad/delete-tag-and-release/blob/master/index.ts#L22).
We wanted to use this Actions to delete multiple tags, but there seems no way (`with` can be used only at once I believe).
The solution would be that `tag_name` accepts an array or a regex. Using an array might be preferable since it makes implementation simpler.

**Comment by thadguidry** [comment]
We could add that feature in the future (or now with a PR from someone) but there are already several existing Actions in the GitHub Actions marketplace that allow bulk deletes as you are suggesting by an array of tags.  The GitHub API could also be called directly and you could pass in your token and iterate over your tag set.

**Comment by thadguidry** [comment]
Or perhaps our other Action is what you need depending on your 
criteria https://github.com/dev-drprasad/delete-older-releases

**Comment by okuramasafumi** [comment]
Thanks, I googled it and found this repository first. I'll look for other Actions that do what we want.
I'll keep this issue open until finding alternative solutions.

**Comment by thadguidry** [comment]
@okuramasafumi do you still need this feature?  or were you able to find an alternative solution?

**Comment by okuramasafumi** [comment]
@thadguidry Currently I don't need this feature anymore. I'll close this for now. Thanks!
