### ISSUE TITLE
Parameter to keep X oldest releases and delete the rest

### ISSUE THREAD

**Issue by thadguidry** [dev-drprasad/delete-tag-and-release#4]
We create a bunch of releases (temp dev versions) of our open source software, OpenRefine.
See for example: https://github.com/OpenRefine/OpenRefine-nightly-releases/releases

It would be nice to use your action where I can specify the following:
1. a repo
2. a new parameter where I specify `keep:3` to keep the 3 latest releases and it then deletes all the older releases (with their attached tag and binary files), completely removing them.

Any chance you could add that option?
Or a brand new action called `delete-older-releases` ?
I looked around and didn't find something that would work.  But pointers welcome.

**Comment by dev-drprasad** [comment]
@thadguidry Deleting multiple tags and releases contradicts with goal of this action. This action goal is to delete all release of a given tag.

I  making new action to satisfy requirements you mentioned
https://github.com/dev-drprasad/delete-multiple-releases
Its not completed yet. You can keep an eye that repo

**Comment by thadguidry** [comment]
@dev-drprasad Awesome!  We are looking forward to it!  Thanks so much!

**Comment by dev-drprasad** [comment]
@thadguidry I released first version of https://github.com/dev-drprasad/delete-older-releases. Please refer README for usage. If you find any issue, do raise an issue
