### ISSUE TITLE
Impossible to override the target repository

### ISSUE THREAD

**Issue by hunomina** [dev-drprasad/delete-tag-and-release#8]
Hi 😄 ! I'd like to be able to set the repository from which the tag/release should be deleted.

Overriding it by setting `env.GITHUB_REPOSITORY` does not work.
It seems like this variable can not be overridden. Or maybe I'm doing this wrong 😞

I've created [this PR](https://github.com/dev-drprasad/delete-tag-and-release/pull/7) in order to solve this 😄 I've made it work on test repositories.
Access rights are not a problem if `env.GITHUB_TOKEN` is set with an appropriate personal access token.

**Comment by dev-drprasad** [comment]
I released newer version v0.2.0. If you're using this action in your project, let me know if it is working as expected

**Comment by hunomina** [comment]
0.2.0 ? Shouldn't it be 1.2.0 ? :/

**Comment by dev-drprasad** [comment]
Previous release was v0.1.3. Since we have added a feature not any breaking changes, it make sense to bump up minor version instead major version. I observed people bump up major version when there is breaking change

**Comment by hunomina** [comment]
Ah yes oops, I can't read xD

**Comment by hunomina** [comment]
It works perfectly 👌 Thanks 😄
